### ISSUE TITLE
Add a method in ExtentCucumberAdaptor to get the current scenario, like we have for current step.

### ISSUE THREAD

**Issue by arun-k** [grasshopper7/extentreports-cucumber7-adapter#1]
Add a method in ExtentCucumberAdaptor to get the current scenario, like we have for current step so that additional informations like categories or devices can be added in the code itself.

**Comment by grasshopper7** [comment]
i am not completely sure about the requirement. can u send a PR with the changes? Thx.

**Comment by arun-k** [comment]
@grasshopper7 I have raised a pull request #2 . Please have a look

**Comment by grasshopper7** [comment]
Will merge it and release a new version in a couple of days

**Comment by grasshopper7** [comment]
Have merged and released, Should be available in maven in a matter of hours
