### ISSUE TITLE
Ability to put "extent.properties" file in any location inside "resources" folder

### ISSUE THREAD

**Issue by quangdo8x** [grasshopper7/extentreports-cucumber7-adapter#10]
My practice had includes a few configuration files based on the below structure:

resources
-----config
----------executions
----------report (extent report config files)
-----data
-----features

When using this library, I had to put directly "extent.properties" file under "resources" directory. This makes my resource structures not categorized.

**Comment by siva90144** [comment]
@quangdo8x i agree with you. @grasshopper7 any changes for this?

**Comment by grasshopper7** [comment]
This needs to be handled at the core ExtentReport level and not in the adapter code. I personally do not think this is a big deal, but I could be wrong.
I would suggest you create an issue in the ExtentReport repository. Thx

**Comment by siva90144** [comment]
Thanks to [quangdo8x](https://github.com/quangdo8x) and @grasshopper7 
created : https://github.com/extent-framework/extentreports-java/issues/401
