### ISSUE TITLE
Ability to change Spark report name

### ISSUE THREAD

**Issue by Soumendu-Khilar** [grasshopper7/extentreports-cucumber7-adapter#11]
Is there a way to change the report name from Spark.html to something as desired by the user.

**Comment by grasshopper7** [comment]
u can change this in the extent.properties, with this property - extent.reporter.spark.out. https://github.com/grasshopper7/cuke7-extent-adapter-report/blob/master/cuke7-extent-adapter-report/src/test/resources/extent.properties

**Comment by Soumendu-Khilar** [comment]
In extent properties we can give a static name to the report.
Is there a way fir dynamic names.Such as creating reports with current time as report name.

**Comment by grasshopper7** [comment]
The folder containing the report can be configured with date and time but not the report. Refer to the section 'Customized Report Folder Name' in https://ghchirp.online/3196/
