### ISSUE TITLE
[Feature Request] Ability to generate separate HTML/PDF reports for failed scenarios

### ISSUE THREAD

**Issue by prtraj2** [grasshopper7/extentreports-cucumber7-adapter#14]
I want to make a request to add a capability to generate separate HTML/PDF reports for failed test cases if possible. Especially in the PDF report since we do not have filter functionality like we do in HTML report and when business teams refer the PDF report where focus is just on failed test cases it becomes a hectic task to keep scrolling and identifying failed test case from the whole report.

**Comment by grasshopper7** [comment]
I can have a look at doing this for PDF report. But if it involves major refactoring of existing code then it might be a no go. The Spark html report is not maintained or owned by me, so you will need to create an issue with their repository.

**Comment by prtraj2** [comment]
@grasshopper7 Thanks for the reply. Yes please do include this feature in the PDF report. That will be really helpful. And regarding the spark reporter we could do that already through code for non-cucumber based projects as showcased in this [video](https://www.youtube.com/watch?v=PNAiSOZR0tE). But using your cucumber adapter I am unsure how could we achieve this if possible.

Anyways please include this feature in PDF if it is doable. Thanks for being proactive.

**Comment by grasshopper7** [comment]
Added for spark in version 1.8.2. Refer here https://github.com/grasshopper7/extentreports-cucumber7-adapter/issues/15 for usage. Use this with caution as this can be used for hiding data.

**Comment by grasshopper7** [comment]
v1.8.2 does not work as I forgot Status enum takes 2 parameters. Will fix.

**Comment by grasshopper7** [comment]
Added in 1.8.4
