### ISSUE TITLE
Add support for status filter in Spark report

### ISSUE THREAD

**Issue by grasshopper7** [grasshopper7/extentreports-cucumber7-adapter#15]

**Comment by grasshopper7** [comment]
Added in 1.8.2. Use **extent.reporter.spark.statusfilter** with comma delimited status like **Pass,Fail**.

**Comment by grasshopper7** [comment]
v1.8.2 does not work as I forgot Status enum takes 2 parameters. Will fix.

**Comment by prtraj2** [comment]
Sure @grasshopper7. Thanks for including the feature. I will wait for the final fixed version for spark report. Also please do include the feature in PDF as well.

**Comment by grasshopper7** [comment]
Fixed in 1.8.3
