### ISSUE TITLE
Add support for status filter for PDF report

### ISSUE THREAD

**Issue by grasshopper7** [grasshopper7/extentreports-cucumber7-adapter#16]

**Comment by grasshopper7** [comment]
Added in version 1.8.4

**Comment by prtraj2** [comment]
@grasshopper7 When using status filter the exception tab is not shown in the html report. I used extent.reporter.statusfilter=pass,fail and see that no exception icon is present on the left hand side between tests, category, dashboard, etc.

**Comment by prtraj2** [comment]
Can we have a filter just for the PDF report and not for both html and PDF?

**Comment by grasshopper7** [comment]
> @grasshopper7 When using status filter the exception tab is not shown in the html report. I used extent.reporter.statusfilter=pass,fail and see that no exception icon is present on the left hand side between tests, category, dashboard, etc.

Can u add a link to the generated report?

**Comment by grasshopper7** [comment]
> Can we have a filter just for the PDF report and not for both html and PDF?

I am using an existing functionality of extent report to make this work. Separate report filters will be additional work. Also it will generate reports with different results which I am not sure is the right way to go.
U can create a new issue and I will have a look later on.
