### ISSUE TITLE
Vulnerabilities in Cucumber 7 Extent Reports Adapter Dependency

### ISSUE THREAD

**Issue by tgoswami013** [grasshopper7/extentreports-cucumber7-adapter#17]
Hi,

We are getting vulnerability issue while running project with jfrog. Could you pls update com.fasterxml.jackson.core library to version 2.14.0.

Dependency we are using: https://mvnrepository.com/artifact/tech.grasshopper/extentreports-cucumber7-adapter/1.8.4

Thanks!

**Comment by grasshopper7** [comment]
updated in 1.9.0

**Comment by tgoswami013** [comment]
Thanks a lot!

**Comment by tgoswami013** [comment]
Hi,
 
1. Artifact tech.grasshopper:extent-pdf-report:jar:2.9.0 is missing. On jfrog we are getting 404-children item missing.
2. Also, version 1.9.0 is not listing on [mvn repository](https://mvnrepository.com/artifact/tech.grasshopper/extentreports-cucumber7-adapter).
3. Extent PDF Reporter also has vulnerability could you please update jsoup version to [1.15.3](https://mvnrepository.com/artifact/org.jsoup/jsoup/1.15.3)

Thanks!

**Comment by grasshopper7** [comment]
Usually takes some time for maven to replicate. Added 1.9.1 with further fixes.

**Comment by tgoswami013** [comment]
Thanks!

**Comment by grasshopper7** [comment]
1.9.1 is available in maven.
