### ISSUE TITLE
Vulnerability Issue with Jackson Library

### ISSUE THREAD

**Issue by tgoswami013** [grasshopper7/extentreports-cucumber7-adapter#18]
Hi,

We are still getting issues with Jfrog for Vulnerability in Jackson, and It is still looking for the 2.12 Jackson library instead of 2.14. I also used MVN org.owasp.dependency-check-maven for Vulnerability; It is also highlighting jackson 2.12. Could you please check what is wrong here? Please refer below screenshots

<img width="709" alt="owasp" src="https://user-images.githubusercontent.com/26319976/203243621-c1ebb3a4-1098-4718-8a46-6a8cdf0c3c61.png">

![jfrog](https://user-images.githubusercontent.com/26319976/203244117-51ead747-2d72-4e4c-87ac-033e9b1201ee.jpeg)

**Comment by grasshopper7** [comment]
This is due to the use of shade plugin, which brings in an earlier version of Jackson dependencies.  This was necessary because breaking changes were introduced in cucumber gherkin logic from version 7.3.0. The new code was breaking the adapter code. To avoid having multiple versions based on cucumber versions I added the shade plugin.

I have to figure out a way but currently I do not have a solution nor a definite time frame. Please feel free to use an alternate reporting solution or even better offer a way out. Thanks.

**Comment by grasshopper7** [comment]
I checked Maven and it does not show any vulnerabilities for this artifact. Also the maven dependency tree does not show any jackson jar bought in by the adapter pom. The versions that you mention are only present in the meta-inf\maven\pom files of the shaded jar.

**Comment by tgoswami013** [comment]
Actually, you did an awesome work with extent and most people started switching to your library. With org.owasp.dependency-check-maven and Jfrog we are able to detect this Vulnerability. Some people unable to use dependency because of vulnerability. I will also try to find solution to this and get back to you. We really appreciate your work. Thanks a lot!

**Comment by grasshopper7** [comment]
Can you check how jfrog is checking for this vulnerability? I have never worked on jfrog. I ran the owasp checker on the jar and it is showing the issue.

I have to dig deeper into the inner workings of maven shade plugin. The original  messages.jar is also a shaded jar which is adding complexity.

**Comment by grasshopper7** [comment]
You can use this artifact safely, as I have double checked, as there is no jackson jar dependency bought in or jackson code in the shaded jar. I guess jfrog and owasp are reading the meta-inf\maven\pom files. I have a minimize jar setting in the shade plugin which removes all classes which are not used, which removes the jackson classes.

Currently I am unable to figure out how to remove this entry from these files.

**Comment by grasshopper7** [comment]
Fixed in 1.9.2

**Comment by tgoswami013** [comment]
Hi,

Many thanks, we are not getting this issue.
