### ISSUE TITLE
Display Tags Information

### ISSUE THREAD

**Issue by tgoswami013** [grasshopper7/extentreports-cucumber7-adapter#19]
Is it possible to display tags information along with scenario detail in adapter. Please check the highlighted section in below screenshot.

![tag_info](https://user-images.githubusercontent.com/26319976/204124656-f961e395-9817-4d23-8750-42932ef2cf91.png)

**Comment by grasshopper7** [comment]
I am not sure what you are referring too. Please add  more details.

**Comment by tgoswami013** [comment]
Hi,

In the Tests view section, feature and scenario level tags are not displaying. Tags should be displayed with features and scenarios like they are displayed in the above screenshot, and once the user clicks on that tag, the user should be jumped to the tags section, and the selected tag should be applied.
<img width="253" alt="Screenshot 2022-11-27 at 11 51 09 PM" src="https://user-images.githubusercontent.com/26319976/204152777-19733c7b-39cb-428a-a099-bfa4f841d850.png">

**Comment by grasshopper7** [comment]
It is not possible to add this feature to the Spark reporter as I am not the owner of that code base. The feature you are mentioning is from the Html reporter which has been officially deprecated in extent 5. Though you can generate it from the adapter as I have updated the Html reporter to work with the latest extent version. U can refer to the article about this feature.

To add this feature to the Spark report you will need to contact the extent report author.

**Comment by tgoswami013** [comment]
Thanks, this is helpful information!
