### ISSUE TITLE
Show skipped scenario in report

### ISSUE THREAD

**Issue by sassrobi** [grasshopper7/extentreports-cucumber7-adapter#23]
Hi!
If I tag my scenario (for example `@Ignore`) and configure cucumber to skip these scenarios (for example `@ConfigurationParameter(key = FILTER_TAGS_PROPERTY_NAME, value = "not @Ignore")`) it will be completely excluded from reports instead of marked as "Skipped".
Is there a way to include these scenarios as skipped?

I'm using version `1.10.1` of the adapter, cucumber `7.11.0`, junit-jupiter `5.9.2` and junit-platform-suite `1.9.2`.

**Comment by grasshopper7** [comment]
Hi,
I have not used the JUnit5 style for executing Cucumber features so I could be wrong. This configuration behavaior is same as the 'tags' parameter of CucumberOptions. The scenarios are filtered out and never executed. There is no way extent plugin will have any knowledge of these filtered scenarios to display in the report.

**Comment by sassrobi** [comment]
I was afraid that would be the answer.
Yes, this is same as tags in CucumberOptions. The other way would be JUnit Suite's `@ExcludeTags`, but that way the scenario is completely hidden (even in IDEA logs). With cucumber tags, at least IDEA shows scenario as skipped, that's why I hoped this could work.

Thank you for the answer.
