### ISSUE TITLE
Offline mode? How to set it now

### ISSUE THREAD

**Issue by GhsVilela** [grasshopper7/extentreports-cucumber7-adapter#25]
Hi, after updating my project to use this new version of cucumber 7 adapter my report file is no longer being generated with link references to the local folder, does anyone knows how to fix this?

its like this now:

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/13207060/225403871-2df6727a-68da-4618-ab71-8831418328cb.png">

Should be like this:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/13207060/225403958-f3b4fc98-0089-4a02-adf7-0e315a7381f9.png">

**This is an issue when using the report file with Jenkins since it has a security policy and it doesn't allow external links references.**

**Comment by grasshopper7** [comment]
Set the `offlineMode` to true in spark-config.xml

**Comment by GhsVilela** [comment]
@grasshopper7 I wasn't using this file before, going to try using it now, thank you

**Comment by GhsVilela** [comment]
It worked, thanks @grasshopper7 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
    <configuration>
        <encoding>UTF-8</encoding>
        <documentTitle>HTML Test Report</documentTitle>
        <reportName>Spark Report</reportName>
        <offlineMode>true</offlineMode>
    </configuration>
</extentreports>
```
**extent.properties**

extent.reporter.spark.config=src/test/resources/spark-config.xml
