### ISSUE TITLE
Support lexicographical screenshot ordering

### ISSUE THREAD

**Issue by NielsGnodde** [grasshopper7/extentreports-cucumber7-adapter#28]
First of all thank you for creating and maintaining this adapter!

Recently we encountered a use case where users like to browse the screenshots directly using an image viewer without using the generated report file. 

Some operating systems (Microsoft Windows in this case) order files by lexicographical order causing the screenshots to be displayed in the incorrect order.

Adding leading zeros to the screenshot counter would cause the screenshots to be ordered correctly.

We'll add a pull request which changes the screenshot file naming convention.

**Comment by grasshopper7** [comment]
Hi,
Does it work for you if the counter is the first thing in the file name - 1_embedded.jpg?

**Comment by NielsGnodde** [comment]
> Hi, Does it work for you if the counter is the first thing in the file name - 1_embedded.jpg?

This solution will not work because Windows uses lexicographical ordering and therefore we will encounter the same issue once reaching more than 10 screenshots. 

The filenames are no longer a issue for us because our users no longer directly use the screenshot files. Therefore we are closing this issue as it is no longer relevant for us.
