### ISSUE TITLE
Incorrect scenario count for tags and categories is displayed

### ISSUE THREAD

**Issue by darkPanther2628** [grasshopper7/extentreports-cucumber7-adapter#5]

**Comment by grasshopper7** [comment]
provide a concrete example and related feature files. thx

**Comment by darkPanther2628** [comment]
I have 2 feature files and 4 scenario's that has to be executed. I have added extentreports-cucumber7-adapter as a maven dependency to my project. 

My report is showing the scenario's and feature count correctly but scenario count in tags and categories is incorrect.
Please find below screenshot

I have 4 scenario's but the report shows 8 in total in Tags/categories section

Please find the code in following repository
https://github.com/darkPanther2628/BDDTesy.git

![image](https://user-images.githubusercontent.com/47852742/156893261-0e88d04f-bc3f-432f-ba87-e9e107f92fae.png)
![image](https://user-images.githubusercontent.com/47852742/156893287-44897ade-2b38-40ce-be06-f2b943e35e25.png)


Runner File config :
![image](https://user-images.githubusercontent.com/47852742/156893345-e162c7b1-e830-47f1-8994-305e1e07f381.png)

**Comment by grasshopper7** [comment]
This is a known issue for which a fix is required in the core Extent report code.
Each feature, scenario and scenario outline are converted into Extent Tests. The tag information is cascaded for all the extent tests in the hierarchy. For the @smokeTests tag you will have 2 tests from login.feature and 2 from the login2.feature.

**Comment by AlexBravo95** [comment]
Good morning, dear, I have the same problem. I think that to avoid noise in the client, I will remove the tag from the report.

Thank you and good job with the library

**Comment by grasshopper7** [comment]
This has been fixed in version 1.7.1.
